[package]
name = "akafoe-menu"
version = "0.1.3"
edition = "2021"
authors = ["Bernd Busse <bernd@busse-net.de>"]

[dependencies]
quick-xml = "0.23"
regex = "1.5"
reqwest = { version = "0.11", features = ["blocking"] }
time = { version = "0.3", features = ["local-offset", "formatting", "macros"] }
